.TH "sdb-cli" 1
.SH NAME
sdb-cli \- Mono Soft Debugger Command Line Interface
.SH SYNOPSIS
.B sdb-cli
.SH DESCRIPTION
This is sdb-cli, a command line interface to the Mono ECMA CLI runtime's soft
debugger. It's useful when you want to debug a program without installing a
full-blown GUI debugger like MonoDevelop, or when debugging a command line
application.
.PP
The interface is similar to .NET's MDbg tool as well as GDB, albeit with some
differences in syntax.
.SH AUTHOR
Written by Alex Rønne Petersen for the Mono project.
.SH REPORTING BUGS
Please report bugs to: https://github.com/alexrp/sdb-cli/issues
.SH SEE ALSO
.BR mono(1)
.SH COPYRIGHT
Copyright (C) 2011 Alex Rønne Petersen
.SH WEB SITE
Visit: https://github.com/mono/sdb-cli
